In [3]:
import os 
os.listdir('/kaggle/input/')

['ieee-fraud-detection']

In [4]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df_train_id = pd.read_csv('/kaggle/input/ieee-fraud-detection/train_identity.csv')
df_train_txn = pd.read_csv('/kaggle/input/ieee-fraud-detection/train_transaction.csv')
df_test_id = pd.read_csv('/kaggle/input/ieee-fraud-detection/test_identity.csv')
df_test_txn = pd.read_csv('/kaggle/input/ieee-fraud-detection/test_transaction.csv')

df_sample = pd.read_csv('/kaggle/input/ieee-fraud-detection/sample_submission.csv')

In [10]:
df_train_id.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,TransactionID,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987004,0.0,70787.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M
1,2987008,-5.0,98945.0,NaN,NaN,0.0,-5.0,NaN,NaN,NaN,...,mobile safari 11.0,32.0,1334x750,match_status:1,T,F,F,T,mobile,iOS Device
2,2987010,-5.0,191631.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,Windows
3,2987011,-5.0,221832.0,NaN,NaN,0.0,-6.0,NaN,NaN,NaN,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,NaN
4,2987016,0.0,7460.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,...,chrome 62.0,24.0,1280x800,match_status:2,T,F,T,T,desktop,MacOS

In [11]:
df_train_txn.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
df_test_id.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,TransactionID,id-01,id-02,id-03,id-04,id-05,id-06,id-07,id-08,id-09,...,id-31,id-32,id-33,id-34,id-35,id-36,id-37,id-38,DeviceType,DeviceInfo
0,3663586,-45.0,280290.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,chrome 67.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,MYA-L13 Build/HUAWEIMYA-L13
1,3663588,0.0,3579.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 67.0 for android,24.0,1280x720,match_status:2,T,F,T,T,mobile,LGLS676 Build/MXB48T
2,3663597,-5.0,185210.0,NaN,NaN,1.0,0.0,NaN,NaN,NaN,...,ie 11.0 for tablet,NaN,NaN,NaN,F,T,T,F,desktop,Trident/7.0
3,3663601,-45.0,252944.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 67.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,MYA-L13 Build/HUAWEIMYA-L13
4,3663602,-95.0,328680.0,NaN,NaN,7.0,-33.0,NaN,NaN,NaN,...,chrome 67.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,SM-G9650 Build/R16NW

In [13]:
df_test_txn.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,TransactionID,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,3663549,18403224,31.95,W,10409,111.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3663550,18403263,49.00,W,4272,111.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3663551,18403310,171.00,W,4476,574.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3663552,18403310,284.95,W,10989,360.0,150.0,visa,166.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3663553,18403317,67.95,W,18018,452.0,150.0,mastercard,117.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
print("Full Train Set")
df_train = pd.merge(df_train_txn, df_train_id, on = 'TransactionID', how = 'left' )
df_train.head()

Full Train Set

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M

In [15]:
print("Full Test Set")
df_test = pd.merge(df_test_txn, df_test_id, on = 'TransactionID', how = 'left')
df_test.head()

Full Test Set

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,TransactionID,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,...,id-31,id-32,id-33,id-34,id-35,id-36,id-37,id-38,DeviceType,DeviceInfo
0,3663549,18403224,31.95,W,10409,111.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3663550,18403263,49.00,W,4272,111.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3663551,18403310,171.00,W,4476,574.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3663552,18403310,284.95,W,10989,360.0,150.0,visa,166.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3663553,18403317,67.95,W,18018,452.0,150.0,mastercard,117.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
print("Combined DataSet for EDA ")

df = pd.concat([df_train, df_test], axis=0).reset_index(drop=True)
df.head()

Combined DataSet for EDA

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,id-29,id-30,id-31,id-32,id-33,id-34,id-35,id-36,id-37,id-38
0,2987000,0.0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0.0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0.0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0.0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0.0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# EDA

## Data Overview

In [18]:
print("Shape of train_identity", df_train_id.shape)
print("Shape of test_identity", df_test_id.shape)
print("Shape of train_transaction", df_train_txn.shape)
print("Shape of test_transaction", df_test_txn.shape)

print("\n\nShape of train_full", df_train.shape)
print("Shape of test_full", df_test.shape)

print("\n\nShape of fullSet", df.shape)

Shape of train_identity (144233, 41)
Shape of test_identity (141907, 41)
Shape of train_transaction (590540, 394)
Shape of test_transaction (506691, 393)


Shape of train_full (590540, 434)
Shape of test_full (506691, 433)


Shape of fullSet (1097231, 472)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1097231 entries, 0 to 1097230
Columns: 472 entries, TransactionID to id-38
dtypes: float64(423), int64(3), object(46)
memory usage: 3.9+ GB

In [21]:
df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1097231 entries, 0 to 1097230
Data columns (total 472 columns):
 #    Column          Non-Null Count    Dtype
---   ------          --------------    -----
 0    TransactionID   1097231 non-null  int64
 1    isFraud         590540 non-null   float64
 2    TransactionDT   1097231 non-null  int64
 3    TransactionAmt  1097231 non-null  float64
 4    ProductCD       1097231 non-null  object
 5    card1           1097231 non-null  int64
 6    card2           1079644 non-null  float64
 7    card3           1092664 non-null  float64
 8    card4           1092568 non-null  object
 9    card5           1088425 non-null  float64
 10   card6           1092653 non-null  object
 11   addr1           965916 non-null   float64
 12   addr2           965916 non-null   float64
 13   dist1           453743 non-null   float64
 14   dist2           74063 non-null    float64
 15   P_emaildomain   933583 non-null   object
 16   R_emaildomain   273161 non-null   object
 17   C1              1097228 non-null  float64
 18   C2              1097228 non-null  float64
 19   C3              1097228 non-null  float64
 20   C4              1097228 non-null  float64
 21   C5              1097228 non-null  float64
 22   C6              1097228 non-null  float64
 23   C7              1097228 non-null  float64
 24   C8              1097228 non-null  float64
 25   C9              1097228 non-null  float64
 26   C10             1097228 non-null  float64
 27   C11             1097228 non-null  float64
 28   C12             1097228 non-null  float64
 29   C13             1092483 non-null  float64
 30   C14             1097228 non-null  float64
 31   D1              1089931 non-null  float64
 32   D2              581665 non-null   float64
 33   D3              631211 non-null   float64
 34   D4              851458 non-null   float64
 35   D5              563015 non-null   float64
 36   D6              197970 non-null   float64
 37   D7              99050 non-null    float64
 38   D8              149264 non-null   float64
 39   D9              149264 non-null   float64
 40   D10             1008664 non-null  float64
 41   D11             641426 non-null   float64
 42   D12             133971 non-null   float64
 43   D13             185336 non-null   float64
 44   D14             177381 non-null   float64
 45   D15             996049 non-null   float64
 46   M1              649492 non-null   object
 47   M2              649492 non-null   object
 48   M3              649492 non-null   object
 49   M4              578042 non-null   object
 50   M5              437117 non-null   object
 51   M6              768932 non-null   object
 52   M7              515948 non-null   object
 53   M8              515975 non-null   object
 54   M9              515975 non-null   object
 55   V1              641426 non-null   float64
 56   V2              641426 non-null   float64
 57   V3              641426 non-null   float64
 58   V4              641426 non-null   float64
 59   V5              641426 non-null   float64
 60   V6              641426 non-null   float64
 61   V7              641426 non-null   float64
 62   V8              641426 non-null   float64
 63   V9              641426 non-null   float64
 64   V10             641426 non-null   float64
 65   V11             641426 non-null   float64
 66   V12             1008569 non-null  float64
 67   V13             1008569 non-null  float64
 68   V14             1008569 non-null  float64
 69   V15             1008569 non-null  float64
 70   V16             1008569 non-null  float64
 71   V17             1008569 non-null  float64
 72   V18             1008569 non-null  float64
 73   V19             1008569 non-null  float64
 74   V20             1008569 non-null  float64
 75   V21             1008569 non-null  float64
 76   V22             1008569 non-null  float64
 77   V23             1008569 non-null  float64
 78   V24             1008569 non-null  float64
 79   V25             1008569 non-null  float64
 80   V26             1008569 non-null  float64
 81   V27             1008569 non-null  float64
 82   V28             1008569 non-null  float64
 83   V29             1008569 non-null  float64
 84   V30             1008569 non-null  float64
 85   V31             1008569 non-null  float64
 86   V32             1008569 non-null  float64
 87   V33             1008569 non-null  float64
 88   V34             1008569 non-null  float64
 89   V35             851408 non-null   float64
 90   V36             851408 non-null   float64
 91   V37             851408 non-null   float64
 92   V38             851408 non-null   float64
 93   V39             851408 non-null   float64
 94   V40             851408 non-null   float64
 95   V41             851408 non-null   float64
 96   V42             851408 non-null   float64
 97   V43             851408 non-null   float64
 98   V44             851408 non-null   float64
 99   V45             851408 non-null   float64
 100  V46             851408 non-null   float64
 101  V47             851408 non-null   float64
 102  V48             851408 non-null   float64
 103  V49             851408 non-null   float64
 104  V50             851408 non-null   float64
 105  V51             851408 non-null   float64
 106  V52             851408 non-null   float64
 107  V53             1007236 non-null  float64
 108  V54             1007236 non-null  float64
 109  V55             1007236 non-null  float64
 110  V56             1007236 non-null  float64
 111  V57             1007236 non-null  float64
 112  V58             1007236 non-null  float64
 113  V59             1007236 non-null  float64
 114  V60             1007236 non-null  float64
 115  V61             1007236 non-null  float64
 116  V62             1007236 non-null  float64
 117  V63             1007236 non-null  float64
 118  V64             1007236 non-null  float64
 119  V65             1007236 non-null  float64
 120  V66             1007236 non-null  float64
 121  V67             1007236 non-null  float64
 122  V68             1007236 non-null  float64
 123  V69             1007236 non-null  float64
 124  V70             1007236 non-null  float64
 125  V71             1007236 non-null  float64
 126  V72             1007236 non-null  float64
 127  V73             1007236 non-null  float64
 128  V74             1007236 non-null  float64
 129  V75             995986 non-null   float64
 130  V76             995986 non-null   float64
 131  V77             995986 non-null   float64
 132  V78             995986 non-null   float64
 133  V79             995986 non-null   float64
 134  V80             995986 non-null   float64
 135  V81             995986 non-null   float64
 136  V82             995986 non-null   float64
 137  V83             995986 non-null   float64
 138  V84             995986 non-null   float64
 139  V85             995986 non-null   float64
 140  V86             995986 non-null   float64
 141  V87             995986 non-null   float64
 142  V88             995986 non-null   float64
 143  V89             995986 non-null   float64
 144  V90             995986 non-null   float64
 145  V91             995986 non-null   float64
 146  V92             995986 non-null   float64
 147  V93             995986 non-null   float64
 148  V94             995986 non-null   float64
 149  V95             1096917 non-null  float64
 150  V96             1096917 non-null  float64
 151  V97             1096917 non-null  float64
 152  V98             1096917 non-null  float64
 153  V99             1096917 non-null  float64
 154  V100            1096917 non-null  float64
 155  V101            1096917 non-null  float64
 156  V102            1096917 non-null  float64
 157  V103            1096917 non-null  float64
 158  V104            1096917 non-null  float64
 159  V105            1096917 non-null  float64
 160  V106            1096917 non-null  float64
 161  V107            1096917 non-null  float64
 162  V108            1096917 non-null  float64
 163  V109            1096917 non-null  float64
 164  V110            1096917 non-null  float64
 165  V111            1096917 non-null  float64
 166  V112            1096917 non-null  float64
 167  V113            1096917 non-null  float64
 168  V114            1096917 non-null  float64
 169  V115            1096917 non-null  float64
 170  V116            1096917 non-null  float64
 171  V117            1096917 non-null  float64
 172  V118            1096917 non-null  float64
 173  V119            1096917 non-null  float64
 174  V120            1096917 non-null  float64
 175  V121            1096917 non-null  float64
 176  V122            1096917 non-null  float64
 177  V123            1096917 non-null  float64
 178  V124            1096917 non-null  float64
 179  V125            1096917 non-null  float64
 180  V126            1096917 non-null  float64
 181  V127            1096917 non-null  float64
 182  V128            1096917 non-null  float64
 183  V129            1096917 non-null  float64
 184  V130            1096917 non-null  float64
 185  V131            1096917 non-null  float64
 186  V132            1096917 non-null  float64
 187  V133            1096917 non-null  float64
 188  V134            1096917 non-null  float64
 189  V135            1096917 non-null  float64
 190  V136            1096917 non-null  float64
 191  V137            1096917 non-null  float64
 192  V138            157730 non-null   float64
 193  V139            157730 non-null   float64
 194  V140            157730 non-null   float64
 195  V141            157730 non-null   float64
 196  V142            157730 non-null   float64
 197  V143            158006 non-null   float64
 198  V144            158006 non-null   float64
 199  V145            158006 non-null   float64
 200  V146            157730 non-null   float64
 201  V147            157730 non-null   float64
 202  V148            157730 non-null   float64
 203  V149            157730 non-null   float64
 204  V150            158006 non-null   float64
 205  V151            158006 non-null   float64
 206  V152            158006 non-null   float64
 207  V153            157730 non-null   float64
 208  V154            157730 non-null   float64
 209  V155            157730 non-null   float64
 210  V156            157730 non-null   float64
 211  V157            157730 non-null   float64
 212  V158            157730 non-null   float64
 213  V159            158006 non-null   float64
 214  V160            158006 non-null   float64
 215  V161            157730 non-null   float64
 216  V162            157730 non-null   float64
 217  V163            157730 non-null   float64
 218  V164            158006 non-null   float64
 219  V165            158006 non-null   float64
 220  V166            158006 non-null   float64
 221  V167            276365 non-null   float64
 222  V168            276365 non-null   float64
 223  V169            276194 non-null   float64
 224  V170            276194 non-null   float64
 225  V171            276194 non-null   float64
 226  V172            276365 non-null   float64
 227  V173            276365 non-null   float64
 228  V174            276194 non-null   float64
 229  V175            276194 non-null   float64
 230  V176            276365 non-null   float64
 231  V177            276365 non-null   float64
 232  V178            276365 non-null   float64
 233  V179            276365 non-null   float64
 234  V180            276194 non-null   float64
 235  V181            276365 non-null   float64
 236  V182            276365 non-null   float64
 237  V183            276365 non-null   float64
 238  V184            276194 non-null   float64
 239  V185            276194 non-null   float64
 240  V186            276365 non-null   float64
 241  V187            276365 non-null   float64
 242  V188            276194 non-null   float64
 243  V189            276194 non-null   float64
 244  V190            276365 non-null   float64
 245  V191            276365 non-null   float64
 246  V192            276365 non-null   float64
 247  V193            276365 non-null   float64
 248  V194            276194 non-null   float64
 249  V195            276194 non-null   float64
 250  V196            276365 non-null   float64
 251  V197            276194 non-null   float64
 252  V198            276194 non-null   float64
 253  V199            276365 non-null   float64
 254  V200            276194 non-null   float64
 255  V201            276194 non-null   float64
 256  V202            276365 non-null   float64
 257  V203            276365 non-null   float64
 258  V204            276365 non-null   float64
 259  V205            276365 non-null   float64
 260  V206            276365 non-null   float64
 261  V207            276365 non-null   float64
 262  V208            276194 non-null   float64
 263  V209            276194 non-null   float64
 264  V210            276194 non-null   float64
 265  V211            276365 non-null   float64
 266  V212            276365 non-null   float64
 267  V213            276365 non-null   float64
 268  V214            276365 non-null   float64
 269  V215            276365 non-null   float64
 270  V216            276365 non-null   float64
 271  V217            257158 non-null   float64
 272  V218            257158 non-null   float64
 273  V219            257158 non-null   float64
 274  V220            278732 non-null   float64
 275  V221            278732 non-null   float64
 276  V222            278732 non-null   float64
 277  V223            257158 non-null   float64
 278  V224            257158 non-null   float64
 279  V225            257158 non-null   float64
 280  V226            257158 non-null   float64
 281  V227            278732 non-null   float64
 282  V228            257158 non-null   float64
 283  V229            257158 non-null   float64
 284  V230            257158 non-null   float64
 285  V231            257158 non-null   float64
 286  V232            257158 non-null   float64
 287  V233            257158 non-null   float64
 288  V234            278732 non-null   float64
 289  V235            257158 non-null   float64
 290  V236            257158 non-null   float64
 291  V237            257158 non-null   float64
 292  V238            278732 non-null   float64
 293  V239            278732 non-null   float64
 294  V240            257158 non-null   float64
 295  V241            257158 non-null   float64
 296  V242            257158 non-null   float64
 297  V243            257158 non-null   float64
 298  V244            257158 non-null   float64
 299  V245            278732 non-null   float64
 300  V246            257158 non-null   float64
 301  V247            257158 non-null   float64
 302  V248            257158 non-null   float64
 303  V249            257158 non-null   float64
 304  V250            278732 non-null   float64
 305  V251            278732 non-null   float64
 306  V252            257158 non-null   float64
 307  V253            257158 non-null   float64
 308  V254            257158 non-null   float64
 309  V255            278732 non-null   float64
 310  V256            278732 non-null   float64
 311  V257            257158 non-null   float64
 312  V258            257158 non-null   float64
 313  V259            278732 non-null   float64
 314  V260            257158 non-null   float64
 315  V261            257158 non-null   float64
 316  V262            257158 non-null   float64
 317  V263            257158 non-null   float64
 318  V264            257158 non-null   float64
 319  V265            257158 non-null   float64
 320  V266            257158 non-null   float64
 321  V267            257158 non-null   float64
 322  V268            257158 non-null   float64
 323  V269            257158 non-null   float64
 324  V270            278732 non-null   float64
 325  V271            278732 non-null   float64
 326  V272            278732 non-null   float64
 327  V273            257158 non-null   float64
 328  V274            257158 non-null   float64
 329  V275            257158 non-null   float64
 330  V276            257158 non-null   float64
 331  V277            257158 non-null   float64
 332  V278            257158 non-null   float64
 333  V279            1097216 non-null  float64
 334  V280            1097216 non-null  float64
 335  V281            1089931 non-null  float64
 336  V282            1089931 non-null  float64
 337  V283            1089931 non-null  float64
 338  V284            1097216 non-null  float64
 339  V285            1097216 non-null  float64
 340  V286            1097216 non-null  float64
 341  V287            1097216 non-null  float64
 342  V288            1089931 non-null  float64
 343  V289            1089931 non-null  float64
 344  V290            1097216 non-null  float64
 345  V291            1097216 non-null  float64
 346  V292            1097216 non-null  float64
 347  V293            1097216 non-null  float64
 348  V294            1097216 non-null  float64
 349  V295            1097216 non-null  float64
 350  V296            1089931 non-null  float64
 351  V297            1097216 non-null  float64
 352  V298            1097216 non-null  float64
 353  V299            1097216 non-null  float64
 354  V300            1089931 non-null  float64
 355  V301            1089931 non-null  float64
 356  V302            1097216 non-null  float64
 357  V303            1097216 non-null  float64
 358  V304            1097216 non-null  float64
 359  V305            1097216 non-null  float64
 360  V306            1097216 non-null  float64
 361  V307            1097216 non-null  float64
 362  V308            1097216 non-null  float64
 363  V309            1097216 non-null  float64
 364  V310            1097216 non-null  float64
 365  V311            1097216 non-null  float64
 366  V312            1097216 non-null  float64
 367  V313            1089931 non-null  float64
 368  V314            1089931 non-null  float64
 369  V315            1089931 non-null  float64
 370  V316            1097216 non-null  float64
 371  V317            1097216 non-null  float64
 372  V318            1097216 non-null  float64
 373  V319            1097216 non-null  float64
 374  V320            1097216 non-null  float64
 375  V321            1097216 non-null  float64
 376  V322            158782 non-null   float64
 377  V323            158782 non-null   float64
 378  V324            158782 non-null   float64
 379  V325            158782 non-null   float64
 380  V326            158782 non-null   float64
 381  V327            158782 non-null   float64
 382  V328            158782 non-null   float64
 383  V329            158782 non-null   float64
 384  V330            158782 non-null   float64
 385  V331            158782 non-null   float64
 386  V332            158782 non-null   float64
 387  V333            158782 non-null   float64
 388  V334            158782 non-null   float64
 389  V335            158782 non-null   float64
 390  V336            158782 non-null   float64
 391  V337            158782 non-null   float64
 392  V338            158782 non-null   float64
 393  V339            158782 non-null   float64
 394  id_01           144233 non-null   float64
 395  id_02           140872 non-null   float64
 396  id_03           66324 non-null    float64
 397  id_04           66324 non-null    float64
 398  id_05           136865 non-null   float64
 399  id_06           136865 non-null   float64
 400  id_07           5155 non-null     float64
 401  id_08           5155 non-null     float64
 402  id_09           74926 non-null    float64
 403  id_10           74926 non-null    float64
 404  id_11           140978 non-null   float64
 405  id_12           144233 non-null   object
 406  id_13           127320 non-null   float64
 407  id_14           80044 non-null    float64
 408  id_15           140985 non-null   object
 409  id_16           129340 non-null   object
 410  id_17           139369 non-null   float64
 411  id_18           45113 non-null    float64

In [24]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
TransactionID,1097231.0,3.575333e+06,3.544294e+05,2987000.000,3261307.5,3535615.00,3895931.5,4.170239e+06
isFraud,590540.0,3.499001e-02,1.837546e-01,0.000,0.0,0.00,0.0,1.000000e+00
TransactionDT,1097231.0,1.640384e+07,1.081612e+07,86400.000,6651887.0,14491621.00,26513228.5,3.421434e+07
TransactionAmt,1097231.0,1.348879e+02,2.422407e+02,0.018,42.0,67.95,125.0,3.193739e+04
card1,1097231.0,9.925744e+03,4.893776e+03,1000.000,6019.0,9749.00,14247.5,1.839700e+04
...,...,...,...,...,...,...,...,...
id-22,5062.0,1.533682e+01,5.618032e+00,11.000,14.0,14.00,14.0,4.400000e+01
id-24,4740.0,1.316667e+01,3.222440e+00,10.000,11.0,11.00,15.0,2.600000e+01
id-25,5039.0,3.320431e+02,8.635668e+01,100.000,321.0,321.00,355.0,5.490000e+02
id-26,5047.0,1.527529e+02,3.191700e+01,100.000,137.0,147.00,182.0,2.160000e+02
id-32,70671.0,2.621794e+01,3.601046e+00,8.000,24.0,24.00,32.0,4.800000e+01

In [25]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
TransactionID,1097231.0,NaN,NaN,NaN,3575333.150708,354429.372959,2987000.0,3261307.5,3535615.0,3895931.5,4170239.0
isFraud,590540.0,NaN,NaN,NaN,0.03499,0.183755,0.0,0.0,0.0,0.0,1.0
TransactionDT,1097231.0,NaN,NaN,NaN,16403839.798138,10816121.500271,86400.0,6651887.0,14491621.0,26513228.5,34214345.0
TransactionAmt,1097231.0,NaN,NaN,NaN,134.887897,242.24073,0.018,42.0,67.95,125.0,31937.391
ProductCD,1097231,5,W,800657,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
id-34,72175,2,match_status:2,72174,NaN,NaN,NaN,NaN,NaN,NaN,NaN
id-35,136977,2,T,71650,NaN,NaN,NaN,NaN,NaN,NaN,NaN
id-36,136977,2,F,133287,NaN,NaN,NaN,NaN,NaN,NaN,NaN
id-37,136977,2,T,104697,NaN,NaN,NaN,NaN,NaN,NaN,NaN
id-38,136977,2,F,95058,NaN,NaN,NaN,NaN,NaN,NaN,NaN